package register.model;
// Generated 2015/12/23 �U�� 06:48:20 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team implements java.io.Serializable
{

    private int teamId;

    private Serializable teamName;

    private byte[] teamImage;

    private Set<TeamUser> teamUsers = new HashSet<TeamUser>(0);

    public Team()
    {
    }

    public Team(int teamId, Serializable teamName)
    {
        this.teamId = teamId;
        this.teamName = teamName;
    }

    public Team(int teamId, Serializable teamName, byte[] teamImage,
            Set<TeamUser> teamUsers)
    {
        this.teamId = teamId;
        this.teamName = teamName;
        this.teamImage = teamImage;
        this.teamUsers = teamUsers;
    }

    public int getTeamId()
    {
        return this.teamId;
    }

    public void setTeamId(int teamId)
    {
        this.teamId = teamId;
    }

    public Serializable getTeamName()
    {
        return this.teamName;
    }

    public void setTeamName(Serializable teamName)
    {
        this.teamName = teamName;
    }

    public byte[] getTeamImage()
    {
        return this.teamImage;
    }

    public void setTeamImage(byte[] teamImage)
    {
        this.teamImage = teamImage;
    }

    public Set<TeamUser> getTeamUsers()
    {
        return this.teamUsers;
    }

    public void setTeamUsers(Set<TeamUser> teamUsers)
    {
        this.teamUsers = teamUsers;
    }

    @Override
    public String toString()
    {
        return "Team [teamId=" + teamId + ", teamName=" + teamName
                + ", teamImage=" + Arrays.toString(teamImage) + ", teamUsers="
                + teamUsers + "]";
    }

    
}
