package register.model;
// Generated 2015/12/23 �U�� 08:50:54 by Hibernate Tools 4.3.1.Final

import java.util.Arrays;

/**
 * Team generated by hbm2java
 */
public class TeamBean implements java.io.Serializable
{

    private int teamId;

    private String teamName;

    private byte[] teamImage;

    public TeamBean()
    {
    }

    public TeamBean(int teamId, String teamName)
    {
        this.teamId = teamId;
        this.teamName = teamName;
    }

    public TeamBean(int teamId, String teamName, byte[] teamImage)
    {
        this.teamId = teamId;
        this.teamName = teamName;
        this.teamImage = teamImage;
    }

    public int getTeamId()
    {
        return this.teamId;
    }

    public void setTeamId(int teamId)
    {
        this.teamId = teamId;
    }

    public String getTeamName()
    {
        return this.teamName;
    }

    public void setTeamName(String teamName)
    {
        this.teamName = teamName;
    }

    public byte[] getTeamImage()
    {
        return this.teamImage;
    }

    public void setTeamImage(byte[] teamImage)
    {
        this.teamImage = teamImage;
    }

    @Override
    public String toString()
    {
        return "TeamBean [teamId=" + teamId + ", teamName=" + teamName
                + ", teamImage=" + Arrays.toString(teamImage) + "]";
    }

    
}
