package register.model;
// Generated 2015/12/23 �U�� 06:48:20 by Hibernate Tools 4.3.1.Final

/**
 * TeamUserId generated by hbm2java
 */
public class TeamUserId implements java.io.Serializable
{

    private int userId;

    private int teamId;

    public TeamUserId()
    {
    }

    public TeamUserId(int userId, int teamId)
    {
        this.userId = userId;
        this.teamId = teamId;
    }

    public int getUserId()
    {
        return this.userId;
    }

    public void setUserId(int userId)
    {
        this.userId = userId;
    }

    public int getTeamId()
    {
        return this.teamId;
    }

    public void setTeamId(int teamId)
    {
        this.teamId = teamId;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TeamUserId))
            return false;
        TeamUserId castOther = (TeamUserId) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getTeamId() == castOther.getTeamId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getUserId();
        result = 37 * result + this.getTeamId();
        return result;
    }

    @Override
    public String toString()
    {
        return "TeamUserId [userId=" + userId + ", teamId=" + teamId + "]";
    }
    
    
}
