package com.iii.twentywork.model.bean;
// Generated 2015/12/28 �U�� 11:25:11 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TeamUser generated by hbm2java
 */
public class TeamUserBean implements java.io.Serializable
{

    @Override
    public String toString()
    {
        return "TeamUser [id=" + id + ", team=" + team + ", users=" + users
                + ", post=" + post + ", department=" + department
                + ", extension=" + extension + ", activeDate=" + activeDate
                + ", rights=" + rights + "]";
    }

    private TeamUserIdBean id;

    private TeamBean team;

    private UsersBean users;

    private String post;

    private String department;

    private String extension;

    private Date activeDate;

    private int rights;

    public TeamUserBean()
    {
    }

    public TeamUserBean(TeamUserIdBean id, TeamBean team, UsersBean users, Date activeDate,
            int rights)
    {
        this.id = id;
        this.team = team;
        this.users = users;
        this.activeDate = activeDate;
        this.rights = rights;
    }

    public TeamUserBean(TeamUserIdBean id, TeamBean team, UsersBean users, String post,
            String department, String extension, Date activeDate, int rights)
    {
        this.id = id;
        this.team = team;
        this.users = users;
        this.post = post;
        this.department = department;
        this.extension = extension;
        this.activeDate = activeDate;
        this.rights = rights;
    }
    public TeamUserIdBean getId()
    {
        return this.id;
    }

    public void setId(TeamUserIdBean id)
    {
        this.id = id;
    }

    public TeamBean getTeam()
    {
        return this.team;
    }

    public void setTeam(TeamBean team)
    {
        this.team = team;
    }

    public UsersBean getUsers()
    {
        return this.users;
    }

    public void setUsers(UsersBean users)
    {
        this.users = users;
    }

    public String getPost()
    {
        return this.post;
    }

    public void setPost(String post)
    {
        this.post = post;
    }

    public String getDepartment()
    {
        return this.department;
    }

    public void setDepartment(String department)
    {
        this.department = department;
    }

    public String getExtension()
    {
        return this.extension;
    }

    public void setExtension(String extension)
    {
        this.extension = extension;
    }

    public Date getActiveDate()
    {
        return this.activeDate;
    }

    public void setActiveDate(Date activeDate)
    {
        this.activeDate = activeDate;
    }

    public int getRights()
    {
        return this.rights;
    }

    public void setRights(int rights)
    {
        this.rights = rights;
    }

}
