package com.iii.twentywork.model.bean;
// Generated 2015/12/28 �U�� 11:25:11 by Hibernate Tools 4.3.1.Final

/**
 * TeamUserId generated by hbm2java
 */
public class TeamUserIdBean implements java.io.Serializable
{

    @Override
    public String toString()
    {
        return "TeamUserId [userId=" + userId + ", teamId=" + teamId + "]";
    }

    private int userId;

    private int teamId;

    public TeamUserIdBean()
    {
    }

    public TeamUserIdBean(int userId, int teamId)
    {
        this.userId = userId;
        this.teamId = teamId;
    }

    public int getUserId()
    {
        return this.userId;
    }

    public void setUserId(int userId)
    {
        this.userId = userId;
    }

    public int getTeamId()
    {
        return this.teamId;
    }

    public void setTeamId(int teamId)
    {
        this.teamId = teamId;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TeamUserIdBean))
            return false;
        TeamUserIdBean castOther = (TeamUserIdBean) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getTeamId() == castOther.getTeamId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getUserId();
        result = 37 * result + this.getTeamId();
        return result;
    }

}
