package com.iii.twentywork.model.bean;
// Generated 2015/12/28 �U�� 11:25:11 by Hibernate Tools 4.3.1.Final

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class TeamBean implements java.io.Serializable
{

    @Override
    public String toString()
    {
        return "Team [teamId=" + teamId + ", teamName=" + teamName + "]";
    }

    private int teamId;

    private String teamName;

    private byte[] teamImage;

    private Set<TeamUserBean> teamUsers = new HashSet<TeamUserBean>(0);

    public TeamBean()
    {
    }

    public TeamBean(int teamId, String teamName)
    {
        this.teamId = teamId;
        this.teamName = teamName;
    }

    public TeamBean(int teamId, String teamName, byte[] teamImage,
            Set<TeamUserBean> teamUsers)
    {
        this.teamId = teamId;
        this.teamName = teamName;
        this.teamImage = teamImage;
        this.teamUsers = teamUsers;
    }

    public int getTeamId()
    {
        return this.teamId;
    }

    public void setTeamId(int teamId)
    {
        this.teamId = teamId;
    }

    public String getTeamName()
    {
        return this.teamName;
    }

    public void setTeamName(String teamName)
    {
        this.teamName = teamName;
    }

    public byte[] getTeamImage()
    {
        return this.teamImage;
    }

    public void setTeamImage(byte[] teamImage)
    {
        this.teamImage = teamImage;
    }

    public Set<TeamUserBean> getTeamUsers()
    {
        return this.teamUsers;
    }

    public void setTeamUsers(Set<TeamUserBean> teamUsers)
    {
        this.teamUsers = teamUsers;
    }

}
